version: '3.7'
services:
  backend:
    container_name: backend
    image: emelyanovsergey89/ruchamp_b
    env_file:
      - .env-non-dev
    ports:
      - 8000:8000
    depends_on:
      - db


  db:
    container_name: db
    image: postgres:15
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  frontend:
    container_name: frontend
    image: emelyanovsergey89/ruchamp_f
    ports:
      - 3000:3000
    depends_on:
      - backend


volumes:
  postgres_data: