""".

Revision ID: 0a6d0b745469
Revises: 14f40e9ebce7
Create Date: 2024-02-06 20:39:42.040445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6d0b745469'
down_revision = '14f40e9ebce7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
