"""empty message

Revision ID: 32e6ff60977a
Revises: 4d4ce9d3931a
Create Date: 2024-03-06 16:39:58.930969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32e6ff60977a'
down_revision = '4d4ce9d3931a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MatchPeriod')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MatchPeriod',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"MatchPeriod_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('winner_score', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('loser_score', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['Match.id'], name='MatchPeriod_match_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='MatchPeriod_pkey')
    )
    # ### end Alembic commands ###
