"""..

Revision ID: 357882cfaf00
Revises: bae21f0db854
Create Date: 2024-02-09 20:10:40.784330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357882cfaf00'
down_revision = 'bae21f0db854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
