"""empty message

Revision ID: 4d4ce9d3931a
Revises: 5a2e45223fff
Create Date: 2024-03-05 19:54:55.324330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4ce9d3931a'
down_revision = '5a2e45223fff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
