"""empty message

Revision ID: 537add7be0a1
Revises: 32e6ff60977a
Create Date: 2024-03-06 16:43:22.074945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537add7be0a1'
down_revision = '32e6ff60977a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
