"""empty message

Revision ID: 5a2e45223fff
Revises: e44897144d5f
Create Date: 2024-03-04 07:12:08.568785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2e45223fff'
down_revision = 'e44897144d5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
