""".,.

Revision ID: 5b5784dccb9b
Revises: 833079dc6ff9
Create Date: 2024-02-23 23:34:08.307846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5784dccb9b'
down_revision = '833079dc6ff9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
