"""empty message

Revision ID: 670213f2cbb9
Revises: 537add7be0a1
Create Date: 2024-03-25 17:24:14.745887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670213f2cbb9'
down_revision = '537add7be0a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
