""",.,

Revision ID: 6f0b3a93665e
Revises: dfd9af01ef7a
Create Date: 2024-02-19 23:16:36.451233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0b3a93665e'
down_revision = 'dfd9af01ef7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
