"""...

Revision ID: 7b7f2a8ca72f
Revises: d40f9a5c183f
Create Date: 2024-02-17 20:21:36.310953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7f2a8ca72f'
down_revision = 'd40f9a5c183f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
