"""..

Revision ID: 8079e6e05583
Revises: 0e0953ddb6b1
Create Date: 2024-02-17 07:19:08.037605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8079e6e05583'
down_revision = '0e0953ddb6b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
