"""Initial migration

Revision ID: 814dcae24fc8
Revises: 
Create Date: 2024-01-31 12:29:19.818811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814dcae24fc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captain', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('invite_link', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['captain'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TeamMember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team'], ['Team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('SystemAdministrator', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('SystemAdministrator', sa.Column('country', sa.String(), nullable=True))
    op.add_column('SystemAdministrator', sa.Column('photo_url', sa.String(), nullable=True))
    op.drop_column('SystemAdministrator', 'contact_phone')
    op.drop_column('SystemAdministrator', 'nick_name')
    op.add_column('User', sa.Column('verification_token', sa.String(), nullable=True))
    op.drop_column('User', 'confirmation_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('confirmation_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'verification_token')
    op.add_column('SystemAdministrator', sa.Column('nick_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('SystemAdministrator', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('SystemAdministrator', 'photo_url')
    op.drop_column('SystemAdministrator', 'country')
    op.drop_column('SystemAdministrator', 'gender')
    op.drop_table('TeamMember')
    op.drop_table('Team')
    # ### end Alembic commands ###
