"""Initial revision

Revision ID: 830fc04dcbfb
Revises: 11f8bd96d6eb
Create Date: 2024-02-15 19:53:04.468683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830fc04dcbfb'
down_revision = '11f8bd96d6eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
