""",.,.

Revision ID: 833079dc6ff9
Revises: 6f0b3a93665e
Create Date: 2024-02-19 23:26:39.925578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833079dc6ff9'
down_revision = '6f0b3a93665e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
