"""Initial revision

Revision ID: 8e1f0caf3774
Revises: 0e0953ddb6b1
Create Date: 2024-02-24 14:01:49.547127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1f0caf3774'
down_revision = '0e0953ddb6b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
