"""....

Revision ID: 901f7db28436
Revises: 90b8c311e309
Create Date: 2024-02-17 20:39:55.739144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901f7db28436'
down_revision = '90b8c311e309'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
