"""...

Revision ID: 90b8c311e309
Revises: 7b7f2a8ca72f
Create Date: 2024-02-17 20:25:31.992232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b8c311e309'
down_revision = '7b7f2a8ca72f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
