"""...

Revision ID: 94e7c30b5844
Revises: 0a6d0b745469
Create Date: 2024-02-06 21:30:40.641823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e7c30b5844'
down_revision = '0a6d0b745469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
