"""..

Revision ID: 970f11a642e8
Revises: f46ca3e92419
Create Date: 2024-02-09 19:53:25.731192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970f11a642e8'
down_revision = 'f46ca3e92419'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
