"""Initial revision

Revision ID: 99a7238a2551
Revises: 7f0135c2033d
Create Date: 2024-02-15 12:20:30.569460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a7238a2551'
down_revision = '7f0135c2033d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
