"""Initial revision

Revision ID: bfb0e2e4985e
Revises: 99a7238a2551
Create Date: 2024-02-15 12:20:55.918189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb0e2e4985e'
down_revision = '99a7238a2551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
