"""..

Revision ID: d40f9a5c183f
Revises: 8079e6e05583
Create Date: 2024-02-17 07:24:27.449701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40f9a5c183f'
down_revision = '8079e6e05583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
