""",.,

Revision ID: dfd9af01ef7a
Revises: 4dbfc4243544
Create Date: 2024-02-19 23:15:55.535757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd9af01ef7a'
down_revision = '4dbfc4243544'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
