"""empty message

Revision ID: f1002845218d
Revises: a9f4eb8bda82
Create Date: 2024-02-18 20:50:20.130561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1002845218d'
down_revision = 'a9f4eb8bda82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
