"""..

Revision ID: f46ca3e92419
Revises: ebb8d3b17b6a
Create Date: 2024-02-09 19:52:48.418132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46ca3e92419'
down_revision = 'ebb8d3b17b6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
