"""c

Revision ID: f5501145bd84
Revises: 8e1f0caf3774
Create Date: 2024-03-03 13:47:33.167169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5501145bd84'
down_revision = '8e1f0caf3774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
