"""empty message

Revision ID: 41d51de98571
Revises: a132a4215425
Create Date: 2024-05-07 15:51:59.781844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d51de98571'
down_revision = 'a132a4215425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Temp_draw_participants')
    op.drop_table('AgeCategory')
    op.drop_table('Temp_athlete')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Temp_athlete',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Temp_athlete_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('athlete_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Temp_athlete_pkey')
    )
    op.create_table('AgeCategory',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"AgeCategory_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('min_age', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('max_age', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='AgeCategory_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Temp_draw_participants',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Temp_draw_participants_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age_category', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_category', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade_category', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['age_category'], ['AgeCategory.id'], name='Temp_draw_participants_age_category_fkey'),
    sa.ForeignKeyConstraint(['athlete_id'], ['Athlete.id'], name='Temp_draw_participants_athlete_id_fkey'),
    sa.ForeignKeyConstraint(['grade_category'], ['CategoryType.id'], name='Temp_draw_participants_grade_category_fkey'),
    sa.ForeignKeyConstraint(['weight_category'], ['AllWeightClass.id'], name='Temp_draw_participants_weight_category_fkey'),
    sa.PrimaryKeyConstraint('id', name='Temp_draw_participants_pkey')
    )
    # ### end Alembic commands ###
