"""Initial revision

Revision ID: a132a4215425
Revises: a176f36e2bb0
Create Date: 2024-03-04 13:39:44.268926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a132a4215425'
down_revision = 'a176f36e2bb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
