name: Main Ruchamp Workflow
on:
  push:
    branches:
      - dev
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code  # Имя шага задаём сами
        uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions
      - name: Print project tree
        run: tree .
